name: ci

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

permissions:
  contents: read

jobs:
  node:
    uses: remonenaidoo/swiftbets-platform/.github/workflows/node.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write
